# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: starterkit
  pool: 5
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PWD'] %>
  host: 127.0.0.1
#  socket: /tmp/mysqld.sock

staging:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: <%= ENV['APP_STAGE_MYSQL_DB'] %>
  pool: 5
  wait_timeout: 20
  username: <%= ENV['APP_STAGE_MYSQL_DB'] %>
  password: <%= ENV['APP_STAGE_MYSQL_DB'] %>
  socket: /var/lib/mysql/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database:  <%= ENV['APP_PROD_MYSQL_DB'] %>
  pool: 5
  wait_timeout: 20
  username:  <%= ENV['APP_PROD_MYSQL_USER'] %>
  password:  <%= ENV['APP_PROD_MYSQL_PWD'] %>
  host: localhost
